image_root: '/home/user/Desktop/AliProduct2022/'
ann_root: '/home/user/Desktop/AliProduct2022/'
# coco_gt_root: 'annotation/coco_gt'
dataset: 'aliproduct2'
checkpoint_file_name: 'base_5th_e'

# set pretrained as a file path or an url
pretrained: '/home/user/Desktop/BLIP/output/Retrieval_aliproduct2_filtered/blip_filtered_epoch_5_modified.pt'
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 24
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

